#!/bin/bash
# declare an array called array and define 3 vale
array=(
"https://politi.cc/assets/ui-icons.svg#hamburger-icon--even"
"https://politi.cc/assets/ui-icons.svg#hamburger-icon--odd"
"https://politi.cc/assets/ui-icons.svg#hotdog-icon--even"
"https://politi.cc/assets/ui-icons.svg#hotdog-icon--odd"
"https://politi.cc/assets/ui-icons.svg#plus-icon--even"
"https://politi.cc/assets/ui-icons.svg#plus-icon--odd"
"https://politi.cc/assets/ui-icons.svg#dots-horizontal-icon--even"
"https://politi.cc/assets/ui-icons.svg#dots-horizontal-icon--odd"
"https://politi.cc/assets/ui-icons.svg#dots-vertical-icon--even"
"https://politi.cc/assets/ui-icons.svg#dots-vertical-icon--odd"
"https://politi.cc/assets/ui-icons.svg#squares-horizontal-icon--even"
"https://politi.cc/assets/ui-icons.svg#squares-horizontal-icon--odd"
"https://politi.cc/assets/ui-icons.svg#squares-vertical-icon--even"
"https://politi.cc/assets/ui-icons.svg#squares-vertical-icon--odd"
"https://politi.cc/assets/ui-icons.svg#search-icon"
"https://politi.cc/assets/ui-icons.svg#close-icon"
"https://politi.cc/assets/ui-icons.svg#search-icon--small"
"https://politi.cc/assets/ui-icons.svg#search-icon"


)

# array=("$@")
for i in "${array[@]}"
do
	echo $i
	#  wget -T $TOUT -q $dl -O $file
	# wget $i -P scripts/
	# wget $i -P styles/
	wget $i -P icons/site/
done
